### 1. 에러

1. 문법 에러(Syntax Error)
   - 에러 발생 시  `SyntaxError`라는 키워드와 함께, 에러의 상세 내용을 보여줌.
   - `파일이름`과 `줄번호`, `^` 문자를 통해 파이썬이 코드를 읽어 들일 때(`parser`) 문제가 발생한 위치를 표현함.
   - `parser` 는 줄에서 에러가 감지된 가장 앞의 위치를 가리키는 캐럿(caret)기호(`^`)를 표시함.
   - 콜론이 빠지거나, 따옴표가 빠지거나(E0L 에러), 괄호가 빠지거나(E0F 에러).

2. 예외(Exception)
   - 실행 도중 예상하지 못한 상황(Exception)을 맞이하면, 프로그램 실행을 멈춤
   - 문법적으로는 옳지만 실행시 발생하는 에러
   - **아래 제시된 모든 에러는 `Exception`을 상속받아 이뤄진다.**
   -  `ZeroDivisionError` : 숫자를 0으로 나눌 경우
   - `NameError` : 유효하지 않은, 정의되지 않는 변수를 호출하거나
   - `TypeError` : 유효하지 않은 타입끼리의 연산을 실행하거나, 함수 호출 과정에서 필수 매개변수가 누락되거나 초과될 경우(ex : `1 + '1'`, `round(a)`, `round.sample(a)`, `round.choice(a,6)`)
   - `ValueError` : 자료형은 올바르나 값이 적절하지 않은 경우,  존재하지 않는 값을 찾고자 할 경우(ex: `int('3.5')`, `numbers.index(3)`)
   - `IndexError` : 존재하지 않는 index로 조회할 경우(ex: `empty_list[100]`)
   - `KeyError` : 존재하지 않는 Key로 접근한 경우(ex: `songs['nothing']`)
   - `ModuleNotFoundError` : 존재하지 않는 모듈을 import 하는 경우 (ex: `import Not_import`)
   - `ImportError` : Module은 찾았으나 존재하지 않는 클래스/함수를 가져오는 경우(ex: `import random // random.sampl`)
   - `KeyboardInterrupt` : 사용자가 임의로 실행을 중단한 경우. 주피터 노트북의 정지버튼, 실제 실행 환경에서는 `ctrl`+`c`
   - `IndentationError` : 들여쓰기(Indentation)가 적절하지 않은 경우



---

### 2. 예외 처리(Exception Handling)

1. `try` & `except`

   - ```python
     try:
         <코드 블록 1>
     except:
         <코드 블록 2>
     ```

   - `try` 아래의 코드 블록(code block)을 실행함

   - 예외가 발생되지 않으면, **`except` 없이 실행이 종료됨**

   - 예외가 발생하면, **남은 부분을 수행하지 않고**, `except`가 실행됨

   - ```python
     try:
         num = input()
         print(int(num))
     except ValueError:
         print('숫자를 입력해주세요')
     ```

     예시: ValueError를 잡아내는 경우

   - ```python
     try:
         <코드 블록 1>
     except (예외 1, 예외 2):
         <코드 블록 2>
     except 예외3:
         <코드 블록 3>
     ```

     - 이와 같이 하나 이상의 예외를 모두 구분해서 처리할 수도 있다.
     - 단, **에러가 순차적으로 수행됨**으로, 가장 작은 범주부터 시작해야 한다.

   - ```python
     try:
         <코드 블록 1>
     except 예외 1:
         <코드 블록 2>
     else:
         <코드 블록 3>
     ```

     - 에러가 발생하지 않는 경우 수행되는 문장은 `else`를 이용한다.

     - 모든 `except` 절 뒤에 와야 한다.
     - `try` 절이 예외를 일으키지 않을 때 실행되어야만 하는 코드에 적절하다.

   - ```python
     try:
         <코드 블럭 1>
     except 예외 1:
         <코드 블럭 2>
     finally:
         <코드 블럭 3>
     ```

     - 반드시 수행해야 하는 문장은 `finally`를 활용한다.
     - 즉, 모든 상황에 실행되어야만 하는 코드.
     - 예외의 발생 여부와 관계없이 `try` 문을 떠날 때 항상 실행.

   - ```python
     try:
         <코드 블럭 1>
     except 예외 as err:
         <코드 블럭 2>
     ```

     - 이와 같이 `as` 키워드를 활용하여 에러 메시지를 보여줄 수도 있다.

2. 예외 발생 시키기(Exceptino Raising)

   - `raise`를 통해 예외를 강제로 발생시킬 수 있다.

   - ```python
     raise <에러> ('메세지')
     ```

     - 에러 내용이 없을 경우 아래와 같이 뜬다.

     ```python
     RuntimeError : No active exception to reraise
     ```

   - `as` 키워드를 활용하여 에러 메시지를 보여줄 수도 있다.

   - 보통 **상태를 검증하는데 사용**되며 무조건 `AssertionError`가 발생함.

   - ```python
     assert Boolean expression, error message
     
     assert len([1, 2]) == 1, '길이가 1이 아닙니다.'
     ```

   - 일반적으로 디버깅 용도로 활용된다. bash로 쓸 때 쓰는듯?

   